spring.application.name=scheduling-system

# URL de conexão: protocolo jdbc:postgresql, depois host:porta/nome_do_banco
spring.datasource.url=jdbc:postgresql://localhost:5432/scheduling_system

# usuário do banco (o que você configurou ao instalar o Postgres)
spring.datasource.username=postgres

# senha do banco
spring.datasource.password=1234

# diz ao Hibernate pra criar/atualizar as tabelas automaticamente a partir das entidades
spring.jpa.hibernate.ddl-auto=update

# mostra o SQL gerado no console, útil pra aprender o que o Hibernate está fazendo
spring.jpa.show-sql=true